all:
	g++ -std=c++11 -o client main.cpp Client.cpp Client.h ../shared/FifoManager.cpp ../shared/FifoManager.h ../shared/Tuple.cpp ../shared/Tuple.h ../shared/TupleMessage.cpp ../shared/TupleMessage.h ../shared/TupleValue.cpp ../shared/TupleValue.h

